### PR TITLE
Add docker builder to README

### PR DESCRIPTION
**Pull request by lmangani**
Thanks for this wonderful example! Adding a Docker builder w/ vlang and emcc to reduce the requirements to build

### CODE REVIEW

**Comment by SheatNoisette** [comment]
Thanks for your contribution! I would prefer a Dockerfile with some instructions to build it instead of a prebuilt Docker pushed from a third party. 😊

**Comment by lmangani** [comment]
Sure, as you can inspect the [image](https://hub.docker.com/layers/emscripten-v/qxip/emscripten-v/latest/images/sha256-3d3e9f59574c3f1f265156fccfd2a07fc746a5951bb2de4918d1b09dd0f4127c?context=explore) is a simple wrapper over `emscripten/emsdk` which adds `v` and nothing more. Here it is, in case you want to add it:

```
FROM emscripten/emsdk:latest

# Add vlang
ENV VVV  /opt/vlang
ENV PATH "/opt/vlang::${PATH}"

RUN git clone https://github.com/vlang/v /opt/vlang && cd /opt/vlang && make && ./v symlink
```

**Comment by lmangani** [comment]
PR and instructions updated to execute locally

**Comment by SheatNoisette** [comment]
Thanks, I'll test it later.

**Comment by lmangani** [comment]
Hello @SheatNoisette Did it work out as intended?

**Comment by SheatNoisette** [comment]
Thanks !

**Pull request merged**
